name: "I have issues"

description: "consume the putput of the previous action and create a new issue in the repository"

inputs:
  joke:
    description: "This will become the body of the created issue"
  issue-title:
    description: "every issue needs a tittle, it's nice to supply one, even though you could do this dynamically within your code"
    default: "a joke for you"
    requiered: true
  repo-token:
      description: "Token with permission to do repo thing"

runs:
  using: "node12"
  main: "index.js"